In [ ]:
## conda install pytorch torchvision cpuonly -c pytorch

In [1]:
import torch

In [2]:
import numpy as np

In [3]:
lst=[1,2,3,5,6]

In [4]:
arr=np.array(lst)

In [5]:
tensors=torch.from_numpy(arr)

In [6]:
tensors

tensor([1, 2, 3, 5, 6], dtype=torch.int32)

In [7]:
a=torch.tensor(np.arange(0,15).reshape(5,3))

In [8]:
a

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]], dtype=torch.int32)

In [9]:
b=torch.tensor(np.arange(16,31).reshape(5,3))

In [10]:
b

tensor([[16, 17, 18],
        [19, 20, 21],
        [22, 23, 24],
        [25, 26, 27],
        [28, 29, 30]], dtype=torch.int32)

In [11]:
print(a+b)

tensor([[16, 18, 20],
        [22, 24, 26],
        [28, 30, 32],
        [34, 36, 38],
        [40, 42, 44]], dtype=torch.int32)


In [12]:
a.mul(b)

tensor([[  0,  17,  36],
        [ 57,  80, 105],
        [132, 161, 192],
        [225, 260, 297],
        [336, 377, 420]], dtype=torch.int32)